#!/usr/bin/env python3
"""
Create the 22-table ClearBias BCNF schema in PostgreSQL.

Usage (from repo root):
  python -m etl.create_postgres_schema
  python -m etl.create_postgres_schema --drop-first
  python -m etl.create_postgres_schema --verify-only
"""

from __future__ import annotations

import argparse
import time

from postgres_config import connect_postgres

CLEARBIAS_TABLES: tuple[str, ...] = (
    "audit_results",
    "audit_sessions",
    "auditors",
    "ad_content",
    "ad_creatives",
    "age_groups",
    "bias_metrics",
    "bias_scores",
    "campaigns",
    "data_source_metadata",
    "demographics",
    "industries",
    "index_types",
    "interests",
    "performance_logs",
    "platforms",
    "query_templates",
    "regions",
    "system_settings",
    "target_profiles",
    "user_roles",
    "advertisers",
)


def ddl_create_statements() -> list[str]:
    return [
        """
        CREATE TABLE IF NOT EXISTS industries (
            industry_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(200) NOT NULL UNIQUE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS user_roles (
            user_role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            role_name VARCHAR(80) NOT NULL UNIQUE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS index_types (
            index_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type_name VARCHAR(40) NOT NULL UNIQUE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS query_templates (
            query_template_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            sql_code TEXT NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS platforms (
            platform_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(120) NOT NULL UNIQUE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS age_groups (
            age_group_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            min_age INT NOT NULL,
            max_age INT NOT NULL,
            CONSTRAINT chk_age_groups_range CHECK (min_age >= 0 AND max_age >= min_age)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS interests (
            interest_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            interest_name VARCHAR(200) NOT NULL UNIQUE,
            industry_id INT NOT NULL REFERENCES industries (industry_id)
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS ix_interests_industry_id ON interests (industry_id)
        """,
        """
        CREATE TABLE IF NOT EXISTS demographics (
            demographic_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            race VARCHAR(120),
            gender VARCHAR(40),
            income NUMERIC(14, 2)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS target_profiles (
            target_profile_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            profile_name VARCHAR(200) NOT NULL UNIQUE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS regions (
            region_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            city VARCHAR(120),
            state VARCHAR(120),
            country VARCHAR(120) NOT NULL
        )
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_regions_city_state_country
        ON regions (city, state, country)
        """,
        """
        CREATE TABLE IF NOT EXISTS advertisers (
            advertiser_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(300) NOT NULL,
            industry_id INT NOT NULL REFERENCES industries (industry_id)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS campaigns (
            campaign_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            advertiser_id INT NOT NULL REFERENCES advertisers (advertiser_id),
            start_date DATE NOT NULL,
            end_date DATE,
            CONSTRAINT chk_campaigns_dates CHECK (end_date IS NULL OR end_date >= start_date)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS ad_creatives (
            ad_creative_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            campaign_id INT NOT NULL REFERENCES campaigns (campaign_id),
            format VARCHAR(60) NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS ad_content (
            ad_content_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ad_creative_id BIGINT NOT NULL UNIQUE REFERENCES ad_creatives (ad_creative_id),
            headline VARCHAR(500),
            body_text TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS bias_metrics (
            bias_metric_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            metric_name VARCHAR(120) NOT NULL UNIQUE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS bias_scores (
            bias_score_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ad_id BIGINT NOT NULL REFERENCES ad_creatives (ad_creative_id),
            metric_id INT NOT NULL REFERENCES bias_metrics (bias_metric_id),
            score_value NUMERIC(5, 4) NOT NULL,
            measured_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT chk_bias_scores_01 CHECK (score_value BETWEEN 0 AND 1)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS auditors (
            auditor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_role_id INT NOT NULL REFERENCES user_roles (user_role_id),
            name VARCHAR(200) NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS audit_sessions (
            audit_session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            auditor_id INT NOT NULL REFERENCES auditors (auditor_id),
            start_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS audit_results (
            audit_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id BIGINT NOT NULL REFERENCES audit_sessions (audit_session_id),
            summary TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS performance_logs (
            performance_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            query_id INT NOT NULL REFERENCES query_templates (query_template_id),
            index_type_id INT NOT NULL REFERENCES index_types (index_type_id),
            latency_ms NUMERIC(14, 3) NOT NULL CHECK (latency_ms >= 0),
            memory_mb NUMERIC(14, 3) NOT NULL CHECK (memory_mb >= 0),
            logged_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS system_settings (
            system_setting_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            setting_key VARCHAR(120) NOT NULL UNIQUE,
            setting_value TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS data_source_metadata (
            data_source_metadata_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_name VARCHAR(200) NOT NULL UNIQUE,
            record_count BIGINT NOT NULL CHECK (record_count >= 0),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """,
        "CREATE INDEX IF NOT EXISTS ix_advertisers_industry_id ON advertisers (industry_id)",
        "CREATE INDEX IF NOT EXISTS ix_campaigns_advertiser_id ON campaigns (advertiser_id)",
        "CREATE INDEX IF NOT EXISTS ix_ad_creatives_campaign_id ON ad_creatives (campaign_id)",
        "CREATE INDEX IF NOT EXISTS ix_bias_scores_ad_metric ON bias_scores (ad_id, metric_id)",
        "CREATE INDEX IF NOT EXISTS ix_bias_scores_metric ON bias_scores (metric_id)",
        "CREATE INDEX IF NOT EXISTS ix_bias_scores_measured_at ON bias_scores (measured_at)",
    ]


def ddl_drop_statements() -> list[str]:
    return [
        "DROP TABLE IF EXISTS performance_logs CASCADE",
        "DROP TABLE IF EXISTS audit_results CASCADE",
        "DROP TABLE IF EXISTS audit_sessions CASCADE",
        "DROP TABLE IF EXISTS bias_scores CASCADE",
        "DROP TABLE IF EXISTS ad_content CASCADE",
        "DROP TABLE IF EXISTS ad_creatives CASCADE",
        "DROP TABLE IF EXISTS campaigns CASCADE",
        "DROP TABLE IF EXISTS advertisers CASCADE",
        "DROP TABLE IF EXISTS auditors CASCADE",
        "DROP TABLE IF EXISTS bias_metrics CASCADE",
        "DROP TABLE IF EXISTS query_templates CASCADE",
        "DROP TABLE IF EXISTS index_types CASCADE",
        "DROP TABLE IF EXISTS data_source_metadata CASCADE",
        "DROP TABLE IF EXISTS system_settings CASCADE",
        "DROP TABLE IF EXISTS regions CASCADE",
        "DROP TABLE IF EXISTS target_profiles CASCADE",
        "DROP TABLE IF EXISTS demographics CASCADE",
        "DROP TABLE IF EXISTS interests CASCADE",
        "DROP TABLE IF EXISTS age_groups CASCADE",
        "DROP TABLE IF EXISTS platforms CASCADE",
        "DROP TABLE IF EXISTS industries CASCADE",
        "DROP TABLE IF EXISTS user_roles CASCADE",
    ]


def seed_lookup_rows(cur) -> None:
    cur.execute("INSERT INTO user_roles (role_name) VALUES (%s) ON CONFLICT (role_name) DO NOTHING", ("admin",))
    cur.execute("INSERT INTO index_types (type_name) VALUES (%s) ON CONFLICT (type_name) DO NOTHING", ("B-Tree",))
    cur.execute("INSERT INTO index_types (type_name) VALUES (%s) ON CONFLICT (type_name) DO NOTHING", ("PGM",))
    cur.execute(
        "INSERT INTO bias_metrics (metric_name) VALUES (%s) ON CONFLICT (metric_name) DO NOTHING",
        ("Criteo_Click",),
    )


def verify_table_count(cur) -> tuple[int, list[str]]:
    cur.execute(
        """
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = ANY(%s)
        ORDER BY table_name
        """,
        (list(CLEARBIAS_TABLES),),
    )
    found = [r[0] for r in cur.fetchall()]
    return len(found), found


def main() -> int:
    parser = argparse.ArgumentParser(description="Create ClearBias PostgreSQL schema (22 tables).")
    parser.add_argument("--drop-first", action="store_true", help="Drop existing ClearBias tables first.")
    parser.add_argument("--verify-only", action="store_true", help="Only run table verification.")
    args = parser.parse_args()

    conn = connect_postgres()
    cur = conn.cursor()
    try:
        if args.drop_first and not args.verify_only:
            print("Dropping existing ClearBias PostgreSQL tables (if any)...")
            for stmt in ddl_drop_statements():
                cur.execute(stmt)
            conn.commit()

        if not args.verify_only:
            print("Creating 22 BCNF tables in PostgreSQL...")
            t0 = time.perf_counter()
            for stmt in ddl_create_statements():
                cur.execute(stmt)
            seed_lookup_rows(cur)
            conn.commit()
            print(f"DDL committed in {(time.perf_counter() - t0) * 1000:.1f} ms")

        n, names = verify_table_count(cur)
        print("--- Verification: information_schema.tables (filtered) ---")
        for t in names:
            print(f"  {t}")
        print(f"--- Count (ClearBias tables found): {n} (expected {len(CLEARBIAS_TABLES)}) ---")
        if n != len(CLEARBIAS_TABLES):
            missing = sorted(set(CLEARBIAS_TABLES) - set(names))
            if missing:
                print(f"Missing: {missing}")
            return 3
    finally:
        cur.close()
        conn.close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
